//this is a program to generate random number written by Olasoyin Miracle
/*THIS IS ALGORITHM
1: let the random number to be generated by "num"
2: check if the number matches case selection based on switch statement
3: display the color that is mapped with the generated random number
*/

//starting the program

import java.util.Random;
import java.util.Scanner;

public class Random {
	public static void main(String[] args) {
		System.out.println("Welcome to my random number generator\n");
	
	Scanner input = new Scanner(System.in);
	Random value = new Random();
	int num;
	num = value.nextInt(7);
	System.out.print(num);
}
}
